// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh5VXTkU58qtBQuR5qT2i1voePECOFea4',
    appId: '1:720444530363:web:18323c6e327d3d4613939e',
    messagingSenderId: '720444530363',
    projectId: 'expo-instagram-clone',
    authDomain: 'expo-instagram-clone.firebaseapp.com',
    storageBucket: 'expo-instagram-clone.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXB5Wyq38VHdfXyYZnQF3aJen0LMI2GHs',
    appId: '1:720444530363:android:2b54139f9b0acb3213939e',
    messagingSenderId: '720444530363',
    projectId: 'expo-instagram-clone',
    storageBucket: 'expo-instagram-clone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEUqQWzRNDolAJa8GYlkyp4Mp2250udus',
    appId: '1:720444530363:ios:c464e4e1b9f993c113939e',
    messagingSenderId: '720444530363',
    projectId: 'expo-instagram-clone',
    storageBucket: 'expo-instagram-clone.appspot.com',
    iosClientId: '720444530363-49mo8vnfu9vc7fv2efbke673duln1ksh.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramCloneFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEUqQWzRNDolAJa8GYlkyp4Mp2250udus',
    appId: '1:720444530363:ios:c464e4e1b9f993c113939e',
    messagingSenderId: '720444530363',
    projectId: 'expo-instagram-clone',
    storageBucket: 'expo-instagram-clone.appspot.com',
    iosClientId: '720444530363-49mo8vnfu9vc7fv2efbke673duln1ksh.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramCloneFlutter',
  );
}
